package com.yizhao.miniudcu.clog;

import com.yizhao.miniudcu.util.CollectionUtil;

import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 * Created by yzhao on 4/15/17.
 */
public class ClogCookieKeyValue extends AbstractLoggable{

    /**
     * CSV of column data to clog, in this order:
     * - cookie_id,key_id,value,key_ts,last_pixel_ts
     * NOTE:
     * - modification_ts is auto-generated by AbstractLoggable, don't specify explicitly )
     * - dates must be converted to Netezza date string format, suitable for loading
     */
    public String toCsv(Collection<Object> permanentAttributes) {

        List<Object> attributes =
                CollectionUtil.<Object> collect(
                        cookieId,
                        keyId,
                        value,
                        keyTs,
                        lastPixelTs);

        return doToCsv(permanentAttributes, attributes, false);
    }

    public ClogCookieKeyValue(long cookieId, int keyId, String value,
                              Date keyTs, Date lastPixelTs) {
        this.cookieId = cookieId;
        this.keyId = keyId;
        this.value = value;
        this.keyTs = keyTs;
        this.lastPixelTs = lastPixelTs;
    }

    private long cookieId;
    private int keyId;
    private String value;
    private Date keyTs; //creation timestamp
    private Date lastPixelTs;

    public long getCookieId() {
        return cookieId;
    }
    public int getKeyId() {
        return keyId;
    }
    public String getValue() {
        return value;
    }
    public Date getKeyTs() {
        return keyTs;
    }
    public Date getLastPixelTs() {
        return lastPixelTs;
    }
    public void setCookieId(long cookieId) {
        this.cookieId = cookieId;
    }
    public void setKeyId(int keyId) {
        this.keyId = keyId;
    }
    public void setValue(String value) {
        this.value = value;
    }
    public void setKeyTs(Date keyTs) {
        this.keyTs = keyTs;
    }
    public void setLastPixelTs(Date lastPixelTs) {
        this.lastPixelTs = lastPixelTs;
    }

    @Override
    public String toString() {
        return "ClogCookieKeyValue [cookieId=" + cookieId + ", keyId=" + keyId + ", value=" + value + ", keyTs=" + keyTs + ", lastPixelTs=" + lastPixelTs + "]";
    }


}
